README.md

In the intro text there are a couple of links whose `href` is invalid. I.e. `<a href="(http://en.wikipedia.org/wiki/Hash_array_mapped_trie)">hash maps tries</a>`. Clicking on these links results in the browser redirecting to https://code.facebook.com/

Fixed broken links to Wikipedia articles

---

.gitignore
Gruntfile.js
__tests__/flatten.ts
__tests__/slice.ts
dist/immutable.d.ts
package.json
resources/jestPreprocessor.js
resources/node_test.sh
type-definitions/Immutable.d.ts

Speed up the test suite by updating to the current version
of the TypeScript compiler which is ~5x faster than the 1.0
version that was being used previously and caching compiled
TypeScript files.
* Update type definitions and flatten.ts for compatibility
with TS 1.4
* Remove ts-compiler dependency and use the now-public TypeScript
compiler API directly.
Fixes #399
With these changes a full run of the test suite on my laptop goes from ~100s to ~20s on first run and ~10s for subsequent runs where the test files have not changed.
*There is currently a test failure in slice.ts which I'm looking into*

Speed up TypeScript compilation when running test suite

---

contrib/cursor/__tests__/Cursor.ts
contrib/cursor/index.js

Due to defect in the code, calling cursor() on cursor can return improper type
```javascript
var data = Immutable.fromJS({ a: [1, 2, 3] });
var cursor = Cursor.from(data);
var deepCursor = cursor.cursor('a');
deepCursor instanceof IndexedCursor; // fails since is KeyedCursor
```
Originally reported here https://github.com/facebook/immutable-js/pull/297 I decided that it might be a safer fix to continue using argument.length rather than checking undefined since I think it might be valid to use undefined in some circumstances.
So this fix goes back to using argument.length in the makeCursor check, but properly calls it with only 3 arguments from subCursor if subCursor is not called with value.

subCursor (cursor.cursor('a')) returns improper type

---

contrib/cursor/__tests__/Cursor.ts
contrib/cursor/index.d.ts
contrib/cursor/index.js

I tried to add some methods to the Cursor API because they are missing. This solves #346.
I'm not sure if this is the right way to do it, because all other methods extend both KeyedCursorPrototype and IndexedCursorPrototype and this only extends IndexedCursorPrototype. So all feedback is more then welcome!

added List methods push, pop, unshift, shift to List IndexedCursor

---

type-definitions/Immutable.d.ts

hasIn(searchKeyPath) {
return this.getIn(searchKeyPath, NOT_SET) !== NOT_SET;
},

hasIn does not take a notSetValue

---

package.json

This is helpful for newer version of `tsd` which can support inspect npm packages for type definitions.

Adding a typescript field

---

README.md

The file here https://github.com/facebook/immutable-js/blob/master/dist/immutable.d.ts uses lower case, but the instructions on using it uses upper case. They should be consistent and the easiest fix is to lower case the instructions.

Use a lower case 'I' in the typescript reference

---

__tests__/List.ts

Adding some tests that ensure that sending a null argument to List.get() will return undefined.
This is the expected behavior on master, but on [3.7.4](https://github.com/facebook/immutable-js/tree/3.7.4) this is currently failing.
I've created [a branch off of 3.7.4](https://github.com/kevinold/immutable-js/tree/v3.7.4_List_get_null) with [a patch](https://github.com/kevinold/immutable-js/commit/f4f123a32a5833e918cf6f5aa60acb1c6384077b) to show these tests failing.
According to a git bisect, this patch was the "good" patch that introduced the fix for this issue - https://github.com/facebook/immutable-js/commit/e4a1e34bc735055819a216764852b03c81cbc301

Add tests that sending a null argument to List.get() should return undefined

---

_src/src/DocVisitor.js

QualifiedName nodes don't have a `text()` method.
This change (or a similar one) is needed to generate the docs after #647. lmk if there's a better way to implement it!

Handle QualifiedNames

---

type-definitions/Immutable.d.ts

Changes "regardless of if they WHERE explicitly defined," to "regardless of if they WERE explicitly defined."

Fix typo in comment describing List#forEach

---

type-definitions/Immutable.d.ts

If you put a console log into the mapper function i.e. 
```Immutable.Seq.of(1,2,3,4,5,6,7,8).filter(function(x){return x % 2}).map(function(x){console.log('mapper called'); return x * x});```
The mapper only console.logs once.
Similarly, inserting a console.log into the definition of the mappedSequence.get method in the definition of the mapFactory, only shows one invocation.
Docs for Seq should reflect the correct number of calls to map.
Currently it states that filter is called 3 times, and map is called twice.
Filter is called 3 times, but it appears map is only called once, on the single returned value from the .get call.
Screenshot of 3 filter calls and single console.log on map attached.

Map is only called once

---

README.md
dist/immutable.js

Removed the reference to `Object.observe` from the readme. This method is set to be removed [1][2] and will not make for a clear reference. 
gh-pages branch should also be updated to reflect the same change to the `index.html` file, however I am unsure how pull requests work for the gh-pages branch. 
[1] https://esdiscuss.org/topic/an-update-on-object-observe
[2] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe

Removed Object.observe reference from readme.

---

resources/node_test.sh

Without this, failing tests would not produce a non-zero exit code.

Ensure tests script fails if any tasks fail

---

__tests__/zip.ts
package.json
resources/jestPreprocessor.js

This updates the jest preprocessor to work with the new typescript compiler, allowing us to support the newer typescript features like "this' return types.
The new typescript version found a legitimate error in a test file, which is also fixed in this rev

Update to use latest version of typescript

---

dist/immutable.d.ts
type-definitions/Immutable.d.ts

I think my PR is obvious :wink:

Fix toOrderedMap and toOrderedSet method definitions

---

dist/immutable.d.ts
type-definitions/Immutable.d.ts

evenSquares was referenced in an example but should be oddSquares.

Documentation: fix reference to evenSquares in Seq

---

.eslintrc
package.json

This adds an eslintrc file, extended from the fbjs-scripts base eslintrc (which React and Jest also use). I disabled rules that were currently failing, and the `src/` directory lints with no errors.
It doesn't add any automated linting yet, but does allow editors configured for linting to lint individual files.
Related to #742.

Add eslintrc file

---

contrib/cursor/index.d.ts

`cursor/index.d.ts` definitions are inaccessible from other ambient external modules. This is needed, for example, to write definitions for `immstruct`.

Make cursor typescript definition accessible from other ambient external modules

---

type-definitions/Immutable.d.ts

To make them more consistent with the docs for `findLast` and `findLastEntry`, added the word `first` to make explicit that `find` and `findEntry` return the first element for which the predicate returns `true`.

doc fix for find and findEntry

---

README.md

The link in the README (this one: https://www.npmjs.com/package/immutable/1.4.1) is a 404. I suggest linking to the repository itself, at your convenience.

Fix broken link to npm's original immutable package

---

type-definitions/immutable.js.flow

I've took a quick look and changed some stuff.
In general very solid.
I've removed the booleany = any type as mixed is favored over any for this. It's used for checks that require a truthy or falsy value. Flow doesn't have them, but mixed allows the return values to be any but won't loose any types. Any would loose them.

Update flow Libdefs

---

type-definitions/immutable.js.flow

As discussed here: https://github.com/facebook/immutable-js/pull/805#issuecomment-210793138 the new Record libdef broke old code.
I've relaxed it again to any. We will loose comfort but it will not error.
Ideas to improve exist, can't do them yet though.
Also fixed errors I've introduced with the last PR. (minor)

Relax Record class for now

---

type-definitions/immutable.js.flow

filter is no longer declared on Iterable.
This is to degrade the Type of a Iterable to any. Mainly to allow following:
```javascript
function foo(): List<number> {
return List([undefined, 1, 2]).filter(i => i); //List no longer contains undefined. Without degrade to generic List it would error.
}
```
flatten is also declared on each Class to return the "correct" type. Before Iterable was returned. This results in missing chaining.
```javascript
List().flatten().map() // Errored before as map is not defined on Iterable
```
get no longer returns ?T but T.
Technically it is not correct, but it allows common use cases and is in sync with the typescript libdef.
Also fixed bugs with get introducing undefined into the Type of a Iterable. (Ordering of overloaded function declarations is …

Improve Flow libdefs

---

.gitignore

Ignore the `.idea` folder to avoid tracking changes as a result of using the JetBrains WebStorm IDE.

ignore JetBrains WebStorm IDE config folder

---

README.md

These links at the bottom of https://facebook.github.io/immutable-js/ were broken since they're relative and https://facebook.github.io/immutable-js/LICENSE and https://facebook.github.io/immutable-js/PATENTS don't exist.
This fixes the issue by using the full link instead of the relative link. I poked around regenerating the hg-pages for you guys, but couldn't find an obvious way to do it so heads up someone will have to regenerate them. =]

Nit: Fix License and Patent links for gh-pages

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

TypeScript 2.0 provides a new `--strictNullCheck` option that adds non-nullable types. In order to use this option with Immutable.js, we need to fix the parameter-types of closure-parameters like mappers, predicates and groupers in the Immutable.d.ts type-definitions. 
The parameters of these closures are now marked as optional in the type definitions. Because of that, TS thinks that those parameters might not be passed to the closure, so it always adds an explicit `| undefined` to those types. These parameters are always filled though. Parameters to closure-parameters should not be explicitly marked optional.

Update Immutable.d.ts to support TypeScript 2.0

---

pages/src/docs/src/style.less

Now you can't click `issues` link because of overlapping.
Fixed by adding `z-index` property to the footer with a value bigger then the sidebar has.

Website fixup: don't overlap the footer with sidebar

---

pages/src/docs/src/SideBar.js
pages/src/docs/src/TypeDocumentation.js
pages/src/docs/src/index.js
pages/src/docs/src/style.less

Fixes the short page issues mentioned in #852. Didn't mean to push aside #873 but the ability to click on the links in the disclaimer was only part of the problem. An example of this issue on the production documentation site can be seen [here](http://facebook.github.io/immutable-js/docs/#/Record.Class).
Firefox 47
Chrome 50
Safari 9.1.1
on El Capitan 10.11.5

fix #852 footer is behind sidebar and sidebar is cutoff on short pages

---

.travis.yml
package.json
test_type_defs.sh
type-definitions/immutable.js.flow
type-definitions/tests/.flowconfig
type-definitions/tests/immutable-flow.js

I'm using `Flow` with `Immutable` but I found numerous false positives when I was working with it. 
By _false positives_ I mean cases where types were ignored. Most of the time it resulted in types dropping their generic definition (from `T<K,V> -> T`).
This is `WIP` because:
- tests for `Iterable` and `Seq` are not implemented yet
- `merge` on maps ignores types when given a `ESIterable`. It only infers types from plain objects.
- after initialization without type (for instance by calling `Map()`) and setting a value on empty object it doesn't correctly infer types
```
var map: Map<number, string> = Map().set(1, '')
```
This might be a flaw of Flow so feel free to point it here.
---
In f31e5c2 I copied the definition of `$Iterable` to `immutable-js`. I did it for two reasons:
1. It …

Flow type declarations test

---

dist/immutable.js
dist/immutable.js.flow
type-definitions/immutable.js.flow
type-definitions/tests/.flowconfig
type-definitions/tests/immutable-flow.js

Adds vanilla JS objects to flow typings of `Immutable.Map`'s `mergeIn` & `mergeDeepIn`.

[Flow]: Add JS objects to Map.mergeIn & Map.mergeDeepIn

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

I've noticed that people new to functional style programming are usually not familiar with the API of `groupBy`. Therefore, added an example to demonstrate it. 
I was hoping to add a few more examples to the docs. Would it be better to submit them as one PR or should each be a separate PR?

added an example for the groupBy method

---

type-definitions/immutable.js.flow
type-definitions/tests/immutable-flow.js

Unfortunately extending Set and Map caused issues with OrderedSet
and OrderedMap flow annotations. For example,
```
const orderedSet: OrderedSet<number> = OrderedSet.of(1,2,3);
```
was not valid, because `of` was incorrectly assumed to return a
`Set<number>` rather than an `OrderedSet<number>`.
The fix was to copy and paste the Set and Map flow annotations,
adjusting for OrderedSet and OrderedMap as appropriate.
See #1015 for more details.
----
Add negative flow test cases for OrderedSet and OrderedMap
One thing that came up as a result of this is that it seems
like the current flow definitions are laxer than typescript
definitions. For example, typescript's intersect looks like
```
intersect(...iterables: Array<T>[]): Set<T>
```
whereas flow's intersect looks like
``` …
```

Fix flowtypes for OrderedSet, OrderedMap, toOrderedSet, and toOrderedMap

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

I noticed that the documentation for the `insert`-method was missing a few characters. So I fixed it.

Add missing characters to end of sentence in documentation

---

dist/immutable.js.flow

I noticed this while making #1037. It seems like the changes that were merged in #1027 never got built.

Build with the changes from pull request 1027

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
contrib/cursor/README.md
pages/src/docs/src/DocHeader.js
pages/src/src/Header.js
pages/third_party/typescript/README.md

I noticed a lot of URLs were still on the old http which is no longer cool.
So I updated to https since it's 2017 :tada:
I also fixed a couple dead links for TypeScript 💯

Change http to https in docs

---

dist/immutable.d.ts

Fixes the following typescript error:
All declarations of merged declaration 'Indexed' must be exported or not exported.
Typescript 2.1.4

fix for typescript error

---

gulpfile.js

This PR adds a watcher for any file in the `/type-definitions/` folder and rebuilds the docs on changes. This makes it easier to work on docs and seeing the results without constantly having to rebuild manually.

Rebuild and reload typedefs in dev server on change

---

src/Immutable.js

It would be useful to have access to the hash function in the case where one needs to ensure equality in custom objects. For example, if wanted to use `Immutable.Set()` to store a custom object, the set would contain duplicates:
```
class Principal {
constructor(type, id) {
this.type = type;
this.id = id;
}
}
const principals = [
new Principal('type_0', 'id_0'),
new Principal('type_0', 'id_0')
];
const principalsSet = Immutable.Set().withMutations((set) => {
principals.forEach((principal) => {
set.add(principal);
});
});
principalsSet.size; // 2, but intend for it to be 1
```
In order for `Immutable.Set` to drop duplicate `Principal` objects, I would need to additionally implement `valueOf`, or both `equals` and `hashCode`, on the `Principal` class. Having access to `Immutable.hash()` …

export hash function

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
package.json
type-definitions/Immutable.d.ts

TypeScript supports non nullable types (optionally), and it's very
helpful to know when some function or method could return `undefined` as
well as a valid result.
This PR adds `| undefined` to the return types of the methods, which can
return `undefined` (like, `get`, `find`, etc).

Add '| undefined' to TypeScript definitions, which can return undefined

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

This is implements overloading for `map` methods for all concrete collection classes,
with proper return type.

Typescript typings. Add overloads for `map` method to all classes.

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts

Fixes part of https://github.com/facebook/immutable-js/issues/705
The places I fixed were already documented w/ comments, I searched for "[K," and "(K," and filled in the appropriate stuff. The Iterable stuff wants two arguments to Iterable so I left them commented. I'm not sure what the fix for that is.
This should save you some typing anyway if you plan to do this.

make use of Typescript's tuple notation

---

dist/immutable.js.flow
type-definitions/immutable.js.flow
type-definitions/tests/.flowconfig
type-definitions/tests/es6-collections.js
type-definitions/tests/immutable-flow.js

The flow type definition tests added in #878 relied on declaring a module, which required .flowconfig to explicitly include the flow definition files, and made exports unclear. This reverts some of the structural changes to the immutable.js.flow from that PR and simplifies the .flowconfig test file to ensure tests are against the *local* copy of immutable. This uncovered a few issues with tests including a mistaken sense that types were exportes as classes and that Set intersections were causing issues.
Fixes #961

Test local flow type definitions

---

__tests__/List.ts
__tests__/Map.ts
__tests__/Seq.ts
__tests__/Set.ts
dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

This leverages ES2015 iterators and tuple defintions to dramatically simplify and improve the typescript type definitions for collection and seq constructors.

Simplify constructor function typedefs

---

__tests__/Record.ts
dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

This uses keyof, Partial, and T[K] typescript advanced types to provide much better type correctness for use of Records
Fixes #909

Update Record typedef (ts)

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
dist/immutable.js.flow
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

The equals() function should really accept anything.
As discussed in #876

Improve type for equals()

---

pages/lib/genTypeDefData.js
type-definitions/Immutable.d.ts

This function is very hard to type correctly and can result in accidental ambiguity or mistakes.

Deprecate Map.of()

---

dist/immutable.js.flow
type-definitions/immutable.js.flow
type-definitions/tests/covariance.js
type-definitions/tests/immutable-flow.js
type-definitions/tests/predicates.js

This is a general improvement pass over the flow type definitions to add overrided specialized return types for transforming functions, using this type where appropriate and fixing incorrect types. It also updates to a less condensed style.
Fixes #911
Fixes #859

Improve flow types

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

Actually, result of consturctor of empty collection could be assigned to collection of any type.
fixes #886

Better typings for constructors of empty containers.

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
dist/immutable.js.flow
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

Since OrderedMap extends Map, the inherited types from Map should return `this` when possible.

Improve types for OrderedMap and OrderedSet

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
dist/immutable.js
dist/immutable.js.flow
src/Map.js
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

Instead of existing previous and next. Clarity around incoming new value vs linear order values.
Fixes #539

Change documentation for merge() family to use oldVal and newVal

---

type-definitions/immutable.js.flow

I think I said that `_: empty` works. Well, it no longer works. So I basically did a find and replace with `..._: []` which does work.
My Bad:(

Fix extra args type

---

contrib/cursor/README.md
contrib/cursor/index.js

The immutable-cursor package is just so much better, go use that.
This adds warnings to the readme, to the source, and to console.

Officially deprecate the Cursor API.

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

This adds a quick explainer of the typescript style notation found in docs, upgrades examples to strictly use ES2015+, illustrates importing and no longer relies on toJS in examples to discourage usage.

Improvement pass over code examples in docs.

---

__tests__/List.ts
__tests__/concat.ts
dist/immutable-nonambient.d.ts
dist/immutable.d.ts
dist/immutable.js.flow
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

This adds significant improvements to the definitions for concat.
Fixes #1151

Significant improvments to concat type definitions.

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
dist/immutable.js.flow
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

This adds a more specific override to reduce() to represent the case where no initial reduction is provided.

Improve type for reduce()

---

__tests__/List.ts
dist/immutable-nonambient.d.ts
dist/immutable.d.ts
tslint.json
type-definitions/Immutable.d.ts

This expands the type def of filter() to return a type-limited version of the original type.
Fixes #1152

Improve filter typescript def to leverage predicate functions

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

It's a small PR to fix an unhighlighted example code and wrong variable names

Fix syntax highlighting and variables

---

__tests__/Conversion.ts
__tests__/Equality.ts
__tests__/List.ts
__tests__/Map.ts
__tests__/Record.ts
__tests__/Set.ts
__tests__/Stack.ts
__tests__/flatten.ts
__tests__/groupBy.ts
__tests__/merge.ts
__tests__/minmax.ts
__tests__/slice.ts
__tests__/zip.ts
dist/immutable-nonambient.d.ts
dist/immutable.d.ts
dist/immutable.js.flow
resources/jestPreprocessor.js
tslint.json
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

This adds strictNullChecks to the ts tests, and improves type definitions such that all tests pass. Specifically this adds two significant changes to typescript defs:
* `size` is now correctly typed to not belong on Collection, exist in a nullable way on `Seq`, and exist in a non-nullable way on all concrete collection types (List, Map, etc)
* `zip` and `zipWith` is overridden in all subtypes such that the return type is more correct.
Fixes #1158

Support typescript strictNullChecks

---

dist/immutable.js.flow
type-definitions/immutable.js.flow

Noticed this when I was reading over the flow type definitions.

Fix typo: change 'hiearchy' to 'hierarchy'

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

This allows use of the `has` method as a type guard, while still otherwise acting as a boolean. Resolves #1230.

Change the has method of Record to be a type guard

---

README.md

`Array#map` doesn't exist in ES3.

Readme ES3->ES5

---

dist/immutable.js.flow
package.json
type-definitions/immutable.js.flow
type-definitions/tests/immutable-flow.js

This pull request aims to help out a bit with issues #1240 and #1172 . It does 3 things:
1) Exposes `RecordInstance` for import
2) Changes the return type of some chainable functions to return `this & T` instead of just `this`
3) Uses the new `$ElementType<T, K>` for some better type safety
Note that I cannot seem to get `$ElementType<T, K>` to check `set` properly, but it works fine for `get`. I really don't know why it wouldn't work the same, so any assistance would be appreciated.

Upgrade flow; solidify Record and RecordInstance a bit

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

more type-safe type TS definitions for zipping for up to three lists. I saw something similar is already done for `zipWith`. Anything is better than `any`, and the typescript compiler is smart enough to pick the most precise type definition.
I've confirmed the compiler does pick up the new type definitions in `__tests/zip.ts` line 28 the type of `zipped`, and by extracting variables in a couple other examples in that file, and all seems to work great.

more type-safe types for zip for up to three lists.

---

dist/immutable-nonambient.d.ts
dist/immutable.d.ts
type-definitions/Immutable.d.ts

this tripped me up the other day when i was looking to use `hash()`. I couldn't offhand find another method that indicated which version it appeared in so i just italicized the string.

docs: updates hash() docs to indicate that it's new in v4.0

---

README.md
dist/immutable-nonambient.d.ts
dist/immutable.d.ts
gulpfile.js
pages/lib/markdown.js
pages/lib/runkit-embed.js
pages/src/docs/index.html
pages/src/docs/src/index.js
pages/src/index.html
pages/src/src/base.less
pages/src/src/index.js
type-definitions/Immutable.d.ts

I'd like to propose using RunKit embeds for the examples in immutable's documentation. The way I've implemented it, the existing examples remain as is, but also have a "run it" button on the bottom right. When clicked, a RunKit embed is swapped in and the example becomes runnable and editable:
As you can see from the above gif, we've also taken the time to add native support for Immutable classes into RunKit, so that all the objects show up correctly (you can try this now [here](https://runkit.com/tolmasky/immutable-classes/branches/master/clone)).
Additionally, I made some custom assert.equals/etc so they show up nicely too:
Some technical details:
1. Its designed in such a way that if RunKit is down, the site behaves like before (so no absolute dependency).
2. I've modified the markdown …

Inline runnable examples with RunKit

---

dist/immutable.es.js
package.json
resources/rollup-config-es.js

This PR is aimed to produce an es module build, targeted by bundlers (e.g. rollup & webpack).
This will enable tree shaking on their side, so will fix #1190.

Bundle an es module

---

pages/lib/genTypeDefData.js
type-definitions/Immutable.d.ts

While reading the type def I noticed how the module Collection exported module Keyed etc... and I figured That we could do the same to make the Record.Instance documentation generate correctly. 
This is certainly not a definitive solution but might still be better than no documentation.

Fix genTypeDef for MappedType to make Record documentation work

---

.gitignore
.travis.yml
package.json
resources/gitpublish.sh

This branch can then be used as a "latest" npm dependency, rather than using the master branch for that purpose. This will allow us to remove built dependencies from the checked-in repo.

Adds a script which automatically builds a #npm branch

---

.travis.yml
pages/src/docs/src/DocHeader.js
pages/src/src/Header.js

This adds a version number to the "docs" link on the site to resolve confusion, and ensures docs are only rebuilt on a tagged release so they do not get out of sync with real releases

Only build docs on tagged releases

---

dist/immutable.js.flow
type-definitions/immutable.js.flow
type-definitions/tests/.flowconfig
type-definitions/tests/immutable-flow.js

When a plain object is used as input in some functions and constructors, Flow can now check its prototype - we should explicitly allow null-prototype Objects.
This also fixed a bug in type checking objects passed to Map constructors

Flow type the prototype chain of "plain object" inputs

---

type-definitions/immutable.js.flow
type-definitions/tests/record.js

For example:
```js
import type {RecordFactory, RecordOf} from 'immutable';
const Point2: RecordFactory<{x: number, y: number}> = Record({x:0, y:0});
const aPoint2: RecordOf<{x: number, y: number}> = Point2();
```

Adds RecordFactory<TObj> as a better way to type the result of Record()

---

__tests__/issues.ts
src/List.js
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

Also adds wasAltered() to type definitions, since it was missing.
Fixes #1247

Set wasAltered() to false after List.asImmutable()

---

src/Set.js

Replace's Set's internal representation of Map<V, true> to Map<V, V>, which more closely mirrors Set's own representation of presenting keys and values as the same value.
Fixes #1249

Fix slow iterator for Set

---

type-definitions/Immutable.d.ts

Merge functions accept any iterable, not just collections.
Closes #1303

Fix ts definitions for merge functions

---

.travis.yml

I can't remember why this was added, but it makes builds slower. If removing it remains passing, then we'll merge this.

RFC: What happens if we remove the g++ from travis?

---

type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

Since zipAll results in a collection as long as the longest zipped, it's possible that undefined values will be included - the type should account for this.

zipAll type should predict undefined values

---

__tests__/issues.ts
__tests__/merge.ts
src/List.js
src/Map.js
type-definitions/Immutable.d.ts

The methods `merge()` and `mergeDeep()` were the last places internally to call `fromJS()`, a method that is expensive, and limits the ability to use plain object and array values within immutable collections.
This PR removes fromJS, not doing any deep coercion at all for `merge()` and simply passing object (incl array) values into the `merge()` function recursively for `mergeDeep()` operations, so only coercing those values that expect to be - leaving others alone.
This is breaking because calls to `merge()` previously were implicitly `fromJS()`'d to get deeply immutable collections, however that is no longer the case.
To update code which relied on this behavior, convert `collection.merge(x)` to `collection.merge(fromJS(x))`.
Fixes #1293

BREAKING: no longer deeply coerce argument to merge()

---

__tests__/ObjectSeq.ts
__tests__/OrderedMap.ts
__tests__/concat.ts
__tests__/groupBy.ts
src/CollectionImpl.js
src/Operations.js
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

This fixes a long standing API quirk where `x.toArray()` had different behavior from `[...x]` or `Array.from(x)`.
This is breaking since previously Map, and other keyed collections would provide an array of only values from `.toArray()`, to fix code that relies on this behavior, convert `x.toArray()` to `x.valueSeq().toArray()`.
Likewise, for code that was working around this behavior before, `x.entrySeq().toArray()` can typically be replaced with `x.toArray()`.
Fixes #333

BREAKING: KeyedCollection.toArray() returns array of tuples.

---

resources/jestPreprocessor.js

This replaces type checking of tests with a simple transpile, which makes running tests 10x faster.
This is possible without reducing test coverage by the recent addition of ts-tests which performs type checking against the typescript tests.

Speed up test runs

---

__tests__/Conversion.ts
__tests__/Set.ts
__tests__/concat.ts
__tests__/merge.ts

jest has dramatically improved over the years, and supports Immutable values directly! No need for our custom checker.

Remove the custom "is" matcher in favor of "toEqual"

---

__tests__/merge.ts
src/List.js
src/Map.js
src/Set.js
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow
type-definitions/tests/immutable-flow.js
type-definitions/ts-tests/list.ts

Fixes a long standing issue where "merge" did not treat List as an expected monoid form, overwriting entries as if it were a Map instead. This *changes* `merge` on List to be an alias of `concat` (much like `merge` is an alias for `union` on Set). Other functions like `mergeDeep` and `mergeWith` have been *removed* from List, since they no longer make sense with this behavior. When `mergeDeep` is called on a Map, nested Lists are now concatenated instead of overwritten.
Fixes #406

BREAKING: concat Lists when merging deeply

---

type-definitions/immutable.js.flow

Copied these from `_Collection` type. Little unsure if they should be typed as `mixed` vs `any`?

Add `getIn` and `hasIn` methods to Record flow type

---

__tests__/List.ts
src/List.js
src/Map.js
src/Set.js
type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow
type-definitions/ts-tests/map.ts
type-definitions/ts-tests/ordered-map.ts
type-definitions/ts-tests/ordered-set.ts
type-definitions/ts-tests/set.ts

These methods are extremely similar, but have differing implementations with different performance characteristics. This makes `concat` an alias of `merge`, sharing the implementation for those methods.

BREAKING: Alias `merge` as `concat` for Set and Map collections

---

type-definitions/immutable.js.flow
type-definitions/tests/immutable-flow.js

This adds a flow type for getIn() using the new $Call type to define two new utility type operators: `$KeyOf` and `$ValOf` which are similar to `$ElementType` but work on both Records and Collections.
To keep this PR small, this only addresses `getIn()` - though in a follow up will do other `*In` methods.

Flow types for getIn()

---

type-definitions/immutable.js.flow
type-definitions/tests/immutable-flow.js

Following up #1366, adds flow types aware of keypath for these three methods for List, Map, and Record

Flow types for setIn(), removeIn(), updateIn()

---

type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow

notSetValue was accidentally missing from type definition for Record. Also include some documentation explaining when this value is used.
Fixes #1359

Add Record.get(v, notSetValue) to type defs

---

src/CollectionImpl.js
src/Record.js
src/toJS.js

This factors toJS() into its own function and simplifies the implementation to recurse within only toJS() instead of between toJS() and value.toJS(). Also, instead of sniffing for a .toJS function existing on the value, uses isImmutable() which consolidates this logic and makes it more predictable.

Simplify toJS()

---

src/CollectionImpl.js
src/List.js
src/Map.js
src/Record.js
src/Set.js
src/Stack.js
src/methods/README.md
src/methods/asImmutable.js
src/methods/asMutable.js
src/methods/deleteIn.js
src/methods/getIn.js
src/methods/hasIn.js
src/methods/merge.js
src/methods/mergeDeep.js
src/methods/mergeDeepIn.js
src/methods/mergeIn.js
src/methods/setIn.js
src/methods/toObject.js
src/methods/update.js
src/methods/updateIn.js
src/methods/wasAltered.js
src/methods/withMutations.js

Currently all collection types refer to MapPrototype to access common methods. This not only makes Map a bottleneck in dependency analysis, but it also makes minification more challenging.
This proposes creating a `methods/` subdir that contains these shared methods - split up into files to avoid the same dependency bottleneck issue. Saves 325 minified bytes (modest 17 gz-bytes).

Factor out common methods to avoid prototype sharing.

---

__tests__/merge.ts
src/functional/merge.js
src/methods/merge.js
src/methods/mergeDeep.js
src/methods/mergeDeepIn.js
src/methods/mergeIn.js

This rectifies an inconsistent behavior between `x.merge(y)` and `x.mergeDeep(y)` where merge would use === on leaf values to determine return-self optimizations, while mergeDeep would use is(). Not only was this inconsistent, it was the only place in the library this behavior existed - where everwhere else `===` is used to determine return-self optimization.
Also minor refactor to save a handful of gz-bytes and reduce overhead.

BREAKING: Use === for deep merge equality.

---

__tests__/Map.ts

Adds test to demonstrate usage of Symbol primitive data type as Map key via set method, which does not work upon Map instantiation.
Split from https://github.com/facebook/immutable-js/pull/1392

Adds test to demo key Symbol in Map.set()

---

type-definitions/immutable.js.flow
type-definitions/tests/immutable-flow.js

Unsure what the root issue was, but key types were being incorrectly derived for deeply nested values. Replacing $ElementType with $ValOf seems to fix the issue.
Added the original reported test case that failed before, now passes
Fixes #1398

Fix flow types for Record setIn/getIn deep values.

---

type-definitions/immutable.js.flow
type-definitions/tests/merge.js

These previously did not include $Shape and dubiously allowed incorrect Iterables. Added some helper types to make defining the merge() family more robust, and lift some of those improvements into `record.merge()` as well.
Fixes #1396

Improve flow types for functional merge() definitions.

---

package.json

It seems the current setup for ts-tests doesn't include Immutable.d.ts in the compilation. This is the only way I could find to test Immutable.d.ts for validity.

test(ts-definitions): test Immutable.d.ts validity using tsc

---

__tests__/Map.ts
__tests__/merge.ts

Demonstrates correct handling of Symbol keys in Map.mergeDeep when the Maps are nested, and initialized with Symbol KV tuples instead of plain JS object literals.
Tests were provided in this discussion:
https://github.com/facebook/immutable-js/pull/1392

Adds Map.mergeDeep Symbol tests

---

type-definitions/Immutable.d.ts

Misleading to say it always results itself (it doesn't) and encourages use of withMutations when possible.
Closes #1413

Improve asImmutable() docs

---

type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow
type-definitions/tests/record.js

Not ideal, but this adds dramatically better support for subclassing Records when using Flow. The cost of this is that the default values passed to Record are no longer checked - they should be separately checked :/. I've updated the documentation to show this in the example, as well as including an example of subclassing a Record when using Flow.
Fixes #1388

Improved Flow support for Record subclasses

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md

**what is the change?:**
Adding a document linking to the Facebook Open Source Code of Conduct,
for visibility and to meet Github community standards.
**why make this change?:**
Facebook Open Source provides a Code of Conduct statement for all
projects to follow.
Exposing the COC via a separate markdown file is a standard being
promoted by Github via the Community Profile in order to meet their Open
Source Guide's recommended community standards.
As you can see, adding this file will complete [Immutable.js's Community Profile](https://github.com/facebook/immutable-js/community)
checklist and increase the visibility of our COC.
**test plan:**
Viewing it on my branch -
**issue:**
internal task t23481323

Add Code of Conduct

---

__tests__/merge.ts
src/methods/merge.js

Fixes #1490
Records can have a size property (`collection.size`, in the [existing code](https://github.com/facebook/immutable-js/blob/master/src/methods/merge.js#L31)) that is independent of the calculated immutable Collection `size` property; using `toSeq()` ensures that the Collection.size property is checked instead. Also added a test case to verify the edge case that this resolves.
In debugging the original issue, I found that adding `return this;` to the end of the `RecordType` function in Record.js (https://github.com/facebook/immutable-js/blob/master/src/Record.js#L76) also deals with #1490. This is because that function was getting erroneously invoked from `mergeIntoKeyedWith` when called on a record with `{size: 0}` from `return collection.constructor(iters[0]);`, and adding the …

Fix collection size check in merge

---

README.md

Existing code sample was missing an import and had a syntax error.

Typo fix for code sample in docs

---

type-definitions/Immutable.d.ts

Add specific documentation to `OrderedMap.set` stating that it returns a new OrderedMap and maintains the existing order.
This attempts to avoid confusion between users as the current documentation for this method inherits from `Immutable.Map` which can be understood like an `OrderedMap.set() => Map`, which is wrong, and might lead to uncertainty about the order of the entries. This Pull Request adds the missing bit to the documentation.
[Link to relevant documentation part of OrderedMap.set()](https://facebook.github.io/immutable-js/docs/#/OrderedMap/set)

Add API documentation to OrderedMap.set()

---

index.html

There are two occurrences of `Github` (instead of `GitHub`) on the official [Immutable.js website](https://facebook.github.io/immutable-js/).
This pull requests fixes both typos.

Fix “Github” typos on Immutable.js website

---

type-definitions/Immutable.d.ts

`Map.getIn` does not take the data as its first argument, instead it is operating directly on the Map. The examples showed it correctly and weren't executable.

Fix runnable examples for Map.getIn

---

type-definitions/immutable.js.flow

Nice to meet you ! I always appreciate the wonderful module. The flow-type definition of `RecordFactory<T>` added from v4.0.0-rc.5 is amazing.
Today I made a PR to revert the abolition of the type definition export of `RecordInstance<T>` that was deleted at that time. I usually use an abstract Class that inherits Record like the following repository.(using v4.0.0-rc.4)
https://github.com/takefumi-yoshii/immutablejs-record-oop-example/blob/master/src/abstract.js
`RecordFactory<T>` gives us simplicity, but without the definition of `RecordInstance<T>`, we can not extends SuperClass.That repository solved all type checks. Best regurd !

revert export type of RecordInstance

---

type-definitions/Immutable.d.ts

fix: fix typo in docs. ES3 -> ES5

---

type-definitions/immutable.js.flow

Not sure why it was missing from `updateIn<U>` or `withMutations` arguments.
Fix #1465

add "& T" to some places where it's missing in RecordInstance

---

__tests__/List.ts
__tests__/Map.ts
src/List.js
src/Map.js
type-definitions/Immutable.d.ts

This is a resubmission of #1189 
This makes it so that the `map` methods on List and Map are "safe" and will return the original collection if no modifications were made. It relies on `withMutations` which appears to already do what is desired. I did do some performance testing this time, and the changes seem to actually improve the performance.
I wasn't sure the best benchmarks to use, so let me know of any particular cases I should look more closely at.
Here are the benchmarks I ran and their results:
```
describe('List', function() {
describe('maps values', function() {
var array1024 = [];
for (var ii = 0; ii < 1024; ii++) {
array1024[ii] = ii;
}
var list = Immutable.List(array1024);
it('noops', function() {
list.map(x => x);
});
it('squares', function() {
list.map(x => x * x);
}); …
```

Add safe refs for no-op 'map' for List and Map

---

type-definitions/Immutable.d.ts
type-definitions/immutable.js.flow
type-definitions/ts-tests/map.ts
type-definitions/ts-tests/ordered-map.ts

Because it can be called at any layer in a datastructure merge, we cannot know apriori what types may be considered. For convenience we just use `any`.
Fixes #1513

mergeDeepWith merger is untypable.

---

README.md

While reading immutable-js web docs I've found a broken link under contribution section. 
_We actively welcome pull requests, learn how to contribute._
The link path works on Github. However, that same link is broken on the web docs.
I have updated the link accordingly and it now works on both Github docs and web docs on https://facebook.github.io/immutable-js/.

FIX Broken link in docs

---

.github/CODE_OF_CONDUCT.md
src/utils/isPlainObj.js

While debugging an issue in the wild with our library [boomerang](https://github.com/akamai/boomerang), we uncovered a [bug in webkit](https://bugs.webkit.org/show_bug.cgi?id=187411) that causes `xhr.response` to no longer work with Immutable.js.
You can see the issue reproduce here: 
https://cvazac.netlify.com/xhr-response-constructor-immutable
This small code change works around version 605.1.15 of Safari.

Update isPlainObj to workaround Safari bug

---

type-definitions/Immutable.d.ts

The `Record.Factory` API is great but the current definitions lack a simple way to reference instances of a record (created from a record factory). This adds a `RecordOf<TProps>` which can be used to create interfaces containing records:
```ts
import { Record, RecordOf } from "immutable";
interface Foo {
flag: boolean;
message: string;
}
const FooRecord = Record<Foo>({
flag: false,
message: "DEFAULT"
});
interface Bar {
foo: RecordOf<Foo>;
}
const bar: Bar = {
foo: new FooRecord({ flag: true })
}
```
Currently I've been creating this type in every library so that I can refer to instances and I think Flow has support for something similar.

Add `RecordOf<TProps>` type alias for TypeScript

---

README.md

Unify code examples' in README with the style specified in contribution guide:
- Ending with semicolon
- Spaces in JSON object

Unify Code Examples' Style in README According to the Contribution Guide

---

pages/src/docs/src/Defs.js
type-definitions/Immutable.d.ts

Since ES6 formally defined `class`, Immutable.js docs have been misleading since they produce factory functions instead of class constructors.
This changes "class" to "type" in the docs and ads explicit text explaining the use of `new` for each factory function.
Fixes #1421

Make docs not use `class` terminology

---

__tests__/Record.ts
__tests__/RecordJS.js
src/Record.js
type-definitions/Immutable.d.ts

This ensures Records are printed correctly in debugging contexts and provides a better mechanism for accessing a Record class's record name.
Deprecates the _name field on Record instances

Give Records a displayName

---

src/utils/isPlainObj.js

Specifically look for a function instead of any value
Closes #1623

FIX: support isPlainObj with constructor keys

---

type-definitions/Immutable.d.ts
type-definitions/ts-tests/map.ts
type-definitions/ts-tests/ordered-map.ts

These have caused more issues with typing than they fixed, unfortunately. While the runtime behavior is still supported, TypeScript types can't capture immutable List as Tuple.
Closes #1611

BREAKING: Remove Iterable<T> as tuple from Map constructor types

---

__tests__/Set.ts
src/Set.js

Fixes https://github.com/facebook/immutable-js/issues/1604
As explained in issue, `set.map` would produce a set whose underlying `_map` had mismatched key-value pairs (expected to always be equal for sets). The original code only mapped the value and kept the original set's keys which caused `has` checks (which uses the `_map` keys) to be incorrect.
- Updated the code to use `mapEntries` on the underlying `_map`
- `updateSet` uses `equals` instead of `===` since `mapEntries` produces a different map reference
- Added test to check for this case

fix: set.map produces valid underlying map

---

package.json
yarn.lock

It was removed from the yarn registry due to a security issue, and
this project transitively depends on it via npm-run-all -> ps-tree ->
event-stream.

Fix build error caused by flatmap-stream-0.1.1 yarn registry removal

---

README.md

The `Seq` example using `flip()` has an incorrect result (all 1s).

Fix flip() example under "Seq is lazy"

---

package-lock.json
pages/lib/TypeKind.js
pages/lib/genTypeDefData.js
type-definitions/Immutable.d.ts

This PR replaces all usage of `any` by `unknown`. Using any in Typescript is unsafe because it allows code that does no type checking. Because it could require type checking where it didn't before, it is a breaking change. Also, `unknown` requires [Typescript 3.0](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html).

Replace any by unknown in typescript types

---

type-definitions/Immutable.d.ts

`new OrderedSet().first()` gives a compiler error, because the `NSV` type is not known.
`new OrderedSet<V>('a string').first()` returns type `V | string`
You need to explicitly provide the type to `first()`.
Intuitively you would pass type `V`:
`new OrderedSet().first<V>()` returns type `V`, although it can return `undefined`
The correct way would be:
`new OrderedSet().first<undefined>()` or `new OrderedSet().first(undefined)`, which would return type `V | undefined`
`new OrderedSet<V>().first()` returns type `V | undefined`
`new OrderedSet<V>('a string').first()` returns type `V | string`
Less likely to make misstakes.
Less typing in the common case when you want `undefined` when there is no first value.

Provide default type to first() and last()

---

type-definitions/Immutable.d.ts
type-definitions/ts-tests/map.ts

Migrate https://github.com/immutable-js-oss/immutable-js/pull/209 in main repository
The typescript definition of Map does accept a `Key` only for the array construction syntax.
This way:
```ts
const a = Map<'status' | 'foo', string | null>([['status', 'paid']]); // OK
const a1 = a.get('status'); // OK
const a2 = a.get('unknow-key'); // report error (OK)
const a = Map<'status' | 'foo', string | null>([['status', 'paid'], ['unwanted-key', 'test']]); // report error (OK)
```
But if we use the object notation, the error reporting is wrong
```ts
const b = Map<'status' | 'foo', string | null>({
status: 'paid', // report wrongly "Argument of type '{ status: string; }' is not assignable to parameter of type 'Iterable<["status" | "foo", string | null]>'"
});
const b1 = a.get('status'); // OK …
```

[typescript] Map constructor accept a list of string as key

---

type-definitions/Immutable.d.ts
type-definitions/ts-tests/list.ts
type-definitions/ts-tests/map.ts
type-definitions/ts-tests/ordered-map.ts

Migrate https://github.com/immutable-js-oss/immutable-js/pull/9, that was already a port of https://github.com/immutable-js/immutable-js/pull/1772
Fixes #1466
This caused a lot of pain due runtime Cannot read property 'update' of undefined errors.

Fix type signature of update and mapEntries

---

package-lock.json
package.json
resources/prepare-dist.sh

Since CI jobs run with node v16, this should be a consistency and performance improvement. Adds advisory to ensure NPM version is modern to maintain this fix.

Update to npm lockfile v2

---

.github/workflows/ci.yml
type-definitions/flow-tests/.flowconfig
type-definitions/flow-tests/covariance.js
type-definitions/flow-tests/es6-collections.js
type-definitions/flow-tests/immutable-flow.js
type-definitions/flow-tests/merge.js
type-definitions/flow-tests/predicates.js
type-definitions/flow-tests/record.js
type-definitions/ts-tests/covariance.ts
type-definitions/ts-tests/es6-collections.ts
type-definitions/ts-tests/exports.ts
type-definitions/ts-tests/functional.ts
type-definitions/ts-tests/list.ts
type-definitions/ts-tests/map.ts
type-definitions/ts-tests/ordered-map.ts
type-definitions/ts-tests/ordered-set.ts
type-definitions/ts-tests/range.ts
type-definitions/ts-tests/record.ts
type-definitions/ts-tests/repeat.ts
type-definitions/ts-tests/seq.ts
type-definitions/ts-tests/set.ts
type-definitions/ts-tests/stack.ts
type-definitions/ts-tests/tsconfig.json

Use absolute rather than relative imports in type checking tests, removes the dependency to build before type checking or linting

Fix import references in type checking tests

---

resources/jestPreprocessor.js

jestPreprocessor keeps a cache calculated from the original file content.
The problem here is that the file content is the content of `src/Immutable.js` with all imports:
```js
import { Seq } from './Seq';
import { OrderedMap } from './OrderedMap';
…
```
so if we update a file, let's say `Seq.js`, the Immutable.js file does not change and the cache is not refreshed.
I think that this is a conflict between the `jestResolver` that tells the `jestPreprocessor` to bundle with rollup in non-ci mode.
Running jest is slower, but more predictable (9s vs 6s in my tests)

ignore jest cache (conflict with rollup build)

---

__tests__/List.ts
src/Iterator.js

Fixes https://github.com/immutable-js/immutable-js/issues/1711

Issue with IE11 and missing Symbol.iterator

---

type-definitions/flow-tests/.flowconfig
type-definitions/flow-tests/covariance.js
type-definitions/flow-tests/immutable-flow.js
type-definitions/flow-tests/merge.js
type-definitions/flow-tests/predicates.js
type-definitions/flow-tests/record.js

Does not change the flow version, but does change some of the flow type test files to make the actual changeset around the upgrade more clear.
- Removes syntax no longer supported
- Replaces `ExpectError` with `FlowExpectedError`
- Minor code formatting improvements that help locate errors

Prepare for Flow upgrade by modernizing flow test syntax

---

__tests__/List.ts
__tests__/Map.ts
__tests__/Set.ts
src/CollectionImpl.js

ES collections reuse the method function for iterators when that iteration behavior is expected to be identical, this applies the same for `Set` and adds tests for this behavior

Use ES standard for iterator fmethod reuse

---

__tests__/Map.ts
__tests__/Seq.ts
__tests__/Set.ts
__tests__/fromJS.ts
src/Iterator.js
src/Seq.js
src/fromJS.js
type-definitions/immutable.d.ts

- When calling `Seq(value)` on an iterable value, use the convention of the default iterator method being equal to one of the prototype methods `value.entries()` and `value.keys()` as a clear indication of Keyed or Set style collections.
- Introduces `isEntriesIterable()` and `isKeysIterable()` to capture these patterns.
- Uses them within `Seq()` to produce an entries sequence or set sequence.
- Use the general `Seq()` in the implementation of `fromJS()`, rather than repeating the logic of determining which Seq conversion to apply.
- Replaces this logic with constraints on which values can be converted
- Introduces allowing iterable objects
- Introduces allowing array-likes
- Add `toSet()` as a possible return from the default converter of `fromJS()` in the case the generated Seq is a …

Generalize fromJS() and Seq() to support Sets

---

__tests__/Equality.ts
__tests__/Range.ts
__tests__/slice.ts
__tests__/utils.js
__tests__/zip.ts
jest.config.js
package-lock.json
package.json

I tried to replace https://github.com/immutable-js/immutable-js/pull/1849 by a better version now that jest should [handle async transform](https://jestjs.io/docs/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object) since 27.0.
I did not manage easily to drop this `make-synchronous` or `synckit` call, I got a lot of different issues and I spent a lot of time already on it, but jest 27 does work fine 👍

upgrade to jest 27 and jasmine-check to 1.0.0-rc

---

website/src/static/getVersions.js

Seems like there are scenarios that allow a tag to be created where `taggerdate` is not set, however `creatordate` is always set. This replaces the sort order.
This also uses the `-` prefix to sort in a direction which avoids the need to reverse it later.

Ensure latest version docs are built

---

type-definitions/immutable.d.ts
type-definitions/ts-tests/empty.ts
type-definitions/ts-tests/exports.ts

These functions can be called without arguments. They should not present a type check error and allow defining the types
Fixes #1876

Add correct types for empty Seq and Collection

---

website/src/MemberDoc.tsx
website/src/TypeDocumentation.tsx
website/src/static/getTypeDefs.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

__tests__/Map.ts
__tests__/Record.ts
src/Record.js

This commit fixes a bug introduced by this [change](https://github.com/immutable-js/immutable-js/commit/a9a1612897627a6ad1217bfa0a76203c95e710b1), which removed a check that '._keys' exists on the object being compared in Record.equals. This leads to a runtime uncaught error when a Record instance is compared against a Map instance.

Fix bug in Record.equals when comparing against Map

---

type-definitions/immutable.d.ts
type-definitions/ts-tests/deepCopy.ts
type-definitions/ts-tests/index.d.ts
type-definitions/ts-tests/list.ts
type-definitions/ts-tests/map.ts
type-definitions/ts-tests/record.ts
type-definitions/ts-tests/set.ts

Record.toJS loose the Record type and return something like:
Actually the following code:
```ts
Record({ keyA: 'a', keyB: 'b' });
```
will return this type.
```ts
{
keyA: unknown,
keyB: unknown,
}
```
This PR implement the `DeepCopy` functionnality to handle the deep convertion made by `toJS`
It will now return this:
```ts
{
keyA: string,
keyB: string,
}
```
It does handle recursive types:
```ts
type NestedObject = Record({ map: Map<string, string>(); list: List<string>(); set: Set<string>() });
// type will be : { map: { [key: string]: string }; list: string[]; set: string[]; }
```

better type for Record.toJS

---

type-definitions/immutable.d.ts
type-definitions/ts-tests/from-js.ts

Originally from [KSXGitHub](https://github.com/KSXGitHub) in https://github.com/immutable-js/immutable-js/pull/1617
> With this pull request, fromJS(value) will no longer return any.

Improve type infererence for fromJS

---

README.md

Fix the wrong link of `JavaScript-first API` inside the [README](https://immutable-js.com)'s TOC.

DOCS: wrong link in README

---

__tests__/Comparator.ts
src/Immutable.js
src/PairSorting.js
type-definitions/immutable.d.ts
type-definitions/immutable.js.flow

* `Comparator<T>`, together with the `PairSorting` enum, would make sorting more expressive - without breaking backwards compatibility.

Introduce Comparator and PairSorting

---

perf/List.js
src/CollectionImpl.js

Actually, `some` [is slightly slower than `find`](https://runkit.com/jdeniau/find-vs-some-perf), which it should not.
This PR improves the implementation of `some` to avoid calling `every / not`. I think that this makes the implementation more easy to understand too.
The drawback is that we re-implement a collection iteration there.
According to the benchmark, there is  ~40% gain on list with 100 000 items.

Faster and implementation of `some`

---

type-definitions/immutable.d.ts
type-definitions/ts-tests/deepCopy.ts
type-definitions/ts-tests/record.ts

Fixes #1930
- https://github.com/immutable-js/immutable-js/pull/1922 (handle the `infer Record` did the trick here)

manage to handle toJS circular reference.

---

type-definitions/immutable.d.ts
type-definitions/ts-tests/deepCopy.ts
type-definitions/ts-tests/record.ts

Rolling back partially https://github.com/immutable-js/immutable-js/pull/1932 as it does introduces https://github.com/immutable-js/immutable-js/issues/1957
Fixes #1957

Rollback toJS type due to circular reference error

---

CHANGELOG.md
package.json

Sadly reverting tree-shaking possibility (https://github.com/immutable-js/immutable-js/pull/1888) as it does break. Moreover, as nearly every collection type can be converted to another collection (`Map().toList()` for example), so nearly no code was removed.
I think that if we want to implement this, we might need to rethink this functionality.

Remove tree-shaking possibility (broken)

---

__tests__/Range.ts
__tests__/count.ts
__tests__/zip.ts
src/Range.js
type-definitions/immutable.d.ts
type-definitions/ts-tests/range.ts

Change Range function: force start and end values to be defined

---

README.md

Not sure if it's intended to scroll down the page to the introduction section, or to the actual docs, but regardless, currently the link navigates to the top of the current page (doesn't do anything)

fix Read the Docs link on readme

---

.github/workflows/ci.yml
.prettierignore
package-lock.json
package.json
tstyche.config.json
type-definitions/ts-tests/covariance.ts
type-definitions/ts-tests/deepCopy.ts
type-definitions/ts-tests/empty.ts
type-definitions/ts-tests/es6-collections.ts
type-definitions/ts-tests/tslint.json

Reference https://github.com/immutable-js/immutable-js/issues/1985#issuecomment-1956085576
This PR migrates two type test files to TSTyche. The setup is painless and migration can be done gradually. Hope this makes it easier to review.
The test files were not passed through Prettier before (probably because of some conflict).
Good question: how CI checks should be setup? To test on different versions of TypeScript, I used TSTyche's `target` option. This makes local runs noisy. It would be enough to have `test:types --target 4.5,5.0,current` in CI. @jdeniau what you think?

Migrate type tests to TSTyche

---

type-definitions/ts-tests/covariance.ts
type-definitions/ts-tests/list.ts

This is just a minor change. I noticed that few matchers were not renamed after upgrading TSTyche to v2.

Use renamed matchers in type tests

---

__tests__/Repeat.ts
src/Repeat.js

It seems like there was a mistake in this old commit, when `deepEqual` was switched from an inherited method to a helper function: https://github.com/immutable-js/immutable-js/commit/79e903b986b2dcef24f5200287fc92c1b7d11810#diff-3ef08c64dab5fc92ebb8aecee330d5e7ae6cc8651f95aab2968b392c228dc606R103
Note that this only happens when calling the `.equals` method directly. `Immutable.is(Immutable.Repeat(<value>), undefined)` properly returns false, so this is a very minor issue that's unlikely to happen in practice. I only noticed this because I was looking at the immutable-js source code.

Fix Repeat(<value>).equals(undefined) incorrectly returning true

---

type-definitions/flow-tests/immutable-flow.js
type-definitions/immutable.d.ts
type-definitions/immutable.js.flow
type-definitions/ts-tests/list.ts

Because of the way types are inferred in both TypeScript and Flow, it's possible for the `NSV` (Not-set value) of the `first()` and `last()` methods to be inferred incorrectly. For example:
```ts
const good = List<number>().first(); // Type is properly inferred as number | undefined, because the list may be empty
const bad: number = List<number>().first(); // This is not a type error, even though the types should not be compatible
```
This is quite subtle and it's easy for it to go unnoticed (for example, this went unnoticed for several years in our company's moderately large TypeScript codebase with ~2000 TypeScript files and ~200,000 lines of code). But it can cause bugs because it makes it easy to accidentally ignore the fact that the list may be empty.
This PR adds type tests for the …

Fix type inference for first() and last()

---

type-definitions/immutable.js.flow

The current definition always expects a value to be found. This has caused bugs in projects I have worked on.

[Flow] Add undefined as a possible return value from find and findLast

---

type-definitions/immutable.js.flow

This better reflects the definition in typescript. 
(I meant to change `first() `and `last()` too but it was already done in 5.x)

Update find() and findLast() in flow definitions

---

__tests__/MultiRequire.js

It was skipped in https://github.com/immutable-js/immutable-js/pull/1916/files#diff-a78999dffb020737304e35059783263bb7610859b279189a2c7a46592d5cba04

reset multi require test

---

__tests__/List.ts
src/List.js

Fixes #2003
The EMPTY_LIST singleton is a really old code. It may have been there to avoid calling "makeList", but I don't think that there is a really huge performance impact.

Try to fix issue with empty list that is a singleton

---

.github/workflows/release.yml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Use new version of set-output

---

package-lock.json
package.json
tstyche.config.json
type-definitions/ts-tests/list.ts
type-definitions/ts-tests/map.ts
type-definitions/ts-tests/ordered-map.ts
type-definitions/ts-tests/ordered-set.ts
type-definitions/ts-tests/record.ts
type-definitions/ts-tests/seq.ts
type-definitions/ts-tests/set.ts
type-definitions/ts-tests/stack.ts

First of all, it should feel amazing to release `immutable@5.0.0`. Congrats!
TSTyche 3.0 is coming out later this week. Seems like current release candidate will be published as it is. Release notes can be found [here](https://tstyche.org/releases/tstyche-3).
As I was mentioning before, the `.toMatch()` matcher is deprecated. The `pick()` type utility can be used instead.
By the way, lowest supported Node.js version now is 18.19. That shouldn’t be a problem, or?

Upgrade TSTyche

---

__tests__/List.ts
src/List.js

Hello!
I have added a failing test. I was not sure where to write it, let me know if it should be located elsewhere. I guess the bug comes from a bad copy/paste between VNode.removeBefore() & VNode.removeAfter().
Let me know if there is something missing in this PR.

Fix List.VNode.removeAfter() bug

---

type-definitions/immutable.d.ts

This PR fixes an issue occurring when a sequence is typed as a regular Seq (not an IndexedSeq, keyedSeq, ...). 
Below a code fragment to reproduce the issue:
```typescript
let seq = Seq();
seq = seq.concat(1): // TS error here because seq.concat() return type is Collection<unknown, unknown> instead of Seq<unknown, unknown>
```

fix: proper Typescript typings for Seq.concat()

---

.github/workflows/output_diff.yml

This PR prepare the migration to TS by testing the output file :
It build the base branch and the current PR, and will fail if the builded file is different in than the base branch.
The purpose of that is to migrate files to TypeScript slowly without altering the runtime file. 
I hope that we can work this way without breaking runtime.
If we _need_ to break runtime, then we might want to add `@ts-expect-error` in main branch, and remove / fix it in the next major.

Detect change in dist file when pushing TS files

---

__tests__/List.ts
__tests__/groupBy.ts
src/Collection.js
src/CollectionImpl.js
src/List.js
src/Map.js
src/Operations.js
src/OrderedMap.js
src/OrderedSet.js
src/Range.js
src/Record.js
src/Repeat.js
src/Seq.js
src/Set.js
src/Stack.js
src/methods/merge.js

Hello!
Happy new year 2025!
This PR removes most "return" in constructors. The only one left is in Record.js.  
I have started to work on TypeScript JSDoc comments and noticed that return in constructor would make the migration of the codebase really difficult.  
Also my personal opinion is that removing return in constructors increase readability.  
Anyway, this PR is a prerequisite for a second PR that will come next which introduce JSDoc TypeScript comments in the codebase.  
I have tried to reduce as much as possible the impact on the API but there are still some small breaking changes:
Map, List, Set are now functions. They are not classes anymore. The related classes are MapImpl, ListImpl and SetImpl. Thoses new classes are not exported so IMHO the impact for ImmutableJS users is …

Avoid return in constructors

---

__tests__/updateIn.ts
src/functional/updateIn.js

Fix `Uncaught TypeError: keyPath.slice is not a function` for ArrayLike method

---

type-definitions/immutable.d.ts
type-definitions/ts-tests/functional.ts
type-definitions/ts-tests/map.ts

- We now handle List() in objects for `getIn` calls.
- The root function `getIn` now use the RetrievePath type.
Superseeds #2068

Better getIn TypeScript RetrievePath

---

.github/workflows/ci.yml
README.md
type-definitions/immutable.d.ts
type-definitions/ts-tests/functional.ts
type-definitions/ts-tests/map.ts

Use [const type parameters](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters) for getIn path retrieval.
This feature has been introduced in TS 5.0, which is more than two years old now. This PR drops support for TS < 5.0.

Drop TS 4 support and add `const P extends` for getIn method types

---

src/Range.js

calling new Range will fail with modern classes. 
Do call the factory method instead of the class constructor
Follows https://github.com/immutable-js/immutable-js/pull/2078

Fix issue with "new RangeImpl"

---

package.json
resources/check-build-output.mjs

Follows https://github.com/immutable-js/immutable-js/pull/2081 but uses mjs instead of cjs file

move check-build-output to mjs file

---

website/src/repl/Editor.tsx
website/src/repl/Repl.tsx
website/src/repl/repl.css
website/styles/globals.css

Responsive version is broken 
Responsive version is now working : 
The issue is related to the fact that the container in a flexbox.
The fix does not work for column direction, but it's better than before.
Related : 
- https://stackoverflow.com/a/75423682/2111353
- https://github.com/codemirror/codemirror5/issues/4142
- https://github.com/codemirror/codemirror5/issues/4895

Fix issue with responsive

---

type-definitions/ts-tests/from-js.ts
type-definitions/ts-tests/functional.ts
type-definitions/ts-tests/list.ts
type-definitions/ts-tests/map.ts
type-definitions/ts-tests/ordered-map.ts
type-definitions/ts-tests/record.ts

Primitive type matchers like `.toBeString()` or `.toBeBoolean()` will be removed in the next major TSTyche release. Reference: https://tstyche.org/releases/tstyche-4#matchers
This PR is replacing them with `.toBe()`.
---
I think that `.toBe<number>()` looks more constant. Makes it is easier to move from `.toBe<number>()` to `.toBe<Promise<number>>()`, if the behaviour is changing. It was not clear why using `.toBeNumber()` is anyhow better.

chore: update type tests

---

__tests__/groupBy.ts
src/functional/get.ts
src/functional/remove.ts
src/functional/updateIn.ts
type-definitions/immutable.d.ts

Superseed https://github.com/immutable-js/immutable-js/pull/2100
Revert a change introduced in [Commit 53237d2](https://github.com/immutable-js/immutable-js/commit/53237d24a707e655ad060dd744a9bb9893915cba).
Previously, grouping by a function that might return `undefined` was tolerated, but in the latest version, this now throws.
This PR does add @giggo1604 changes, but improve the TS typing directly

Revert previous assertion as it introduced a regression

---

__tests__/groupBy.ts
src/functional/updateIn.ts

Hello,
While updating our codebase to the latest version of Immutable, we encountered what seems to be a regression in the behavior of `groupBy`.
This change was introduced in [Commit 53237d2](https://github.com/immutable-js/immutable-js/commit/53237d24a707e655ad060dd744a9bb9893915cba).
Previously, grouping by a function that might return `undefined` was tolerated, but in the latest version, this now throws. While the new behavior arguably makes sense—since grouping by `undefined` isn’t very clean—it does appear to be a breaking change, violating semantic versioning.
If this change is considered intentional, it should also be reflected in the type system: the `grouper` function should not be allowed to return `undefined`.
We’d like to clarify the intended direction:
- Was this change …

add simple test to reproduce groupBy regression

---

type-definitions/immutable.d.ts
type-definitions/ts-tests/map.ts

type defintion:
```ts
export type CompactTLV = CompactTLV.Entries
export namespace CompactTLV {
export type Entries = readonly CompactTLV.Entry[]
export type Entry = readonly [tag: number, value: Uint8Array]
}
```
converation code:
```ts
Map(entries)
```
error message:
```
Argument of type 'Entries' is not assignable to parameter of type 'Iterable<[number, Uint8Array<ArrayBufferLike>]>'.
The types returned by '[Symbol.iterator]().next(...)' are incompatible between these types.
Type 'IteratorResult<Entry, undefined>' is not assignable to type 'IteratorResult<[number, Uint8Array<ArrayBufferLike>], any>'.
Type 'IteratorYieldResult<Entry>' is not assignable to type 'IteratorResult<[number, Uint8Array<ArrayBufferLike>], any>'.
Type 'IteratorYieldResult<Entry>' is not assignable to type …
```

fix: allow readonly map entry constructor

---

src/Iterator.ts

Using `X.prototype` is an old code style, and forbid tree-shaking of the library.
As the 6.x branch will migrate to a modern coding style, let's start with the simple Iterator class.
Replace the Immutable.js file by this
```ts
/* eslint-disable import/order */
// import { Seq } from './Seq';
// import { OrderedMap } from './OrderedMap';
// import { List } from './List';
// import { Map } from './Map';
// import { Stack } from './Stack';
// import { OrderedSet } from './OrderedSet';
// import { PairSorting } from './PairSorting';
// import { Set } from './Set';
// import { Record } from './Record';
// import { Range } from './Range';
// import { Repeat } from './Repeat';
// import { is } from './is';
// import { fromJS } from './fromJS';
import isPlainObject from './utils/isPlainObj';
// …
```

clean iterator prototype to allow tree shaking

---

CHANGELOG.md
src/CollectionImpl.js
src/Hash.ts
src/Iterator.ts
src/Math.ts
src/Record.js

All these methods are widely available for a long time now: 
- [Math.imul](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul#browser_compatibility) (edge 12, safary 7, chrome 28, firefox 20)
- [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#browser_compatibility) (edge 12, safary 9, chrome 38, firefox 6)
- [Symbol.iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator#browser_compatibility) (edge 12, safary 10, chrome 43, firefox 36)
- [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#browser_compatibility) (edge 12, safary 8, chrome 36, firefox 6)

Remove widely available methods
