- type-definitions/Immutable.d.ts
Noticed a missing semicolon when I was converting this file to a format that [Flow](https://github.com/facebook/flow) can understand
> Add missing semicolon

- README.md
Phil's (may he rest in peace) contribution is massive by comparison. His name ought to come first (at least.. I think so)
> Minor Readme Update - putting Phil's name first. 

- contrib/cursor/__tests__/Cursor.ts
- contrib/cursor/index.d.ts
- contrib/cursor/index.js
Closes #249. Uses code from @confiks in https://github.com/facebook/immutable-js/pull/250 comment..
> Added set(value). Fixes #249.

- type-definitions/Immutable.d.ts
> Document common pitfall for Maps constructed of JS objects

- __tests__/Seq.ts
> throw error if NaN is passed into take Fixes #552

- type-definitions/Immutable.d.ts
> Update type definitions to match nested Indexed, Keyed, Set variants

- index.html
People like to open the console and tinker with the documentation right there.  Might as well give them the latest version.
> Updated immutable to the latest version

- type-definitions/Immutable.d.ts
Hopefully this will help people new to the library to avoid silly mistakes.
See this issue for more background information https://github.com/facebook/immutable-js/issues/791
> Added caveat to ES6 iterable protocols

- type-definitions/Immutable.d.ts
More appropriate according to http://languagelog.ldc.upenn.edu/nll/?p=4358.
Alternatively: ‘…regardless whether…’ :wink:
> Minor grammar improvement: ‘…regardless of if…’ --> ‘…regardless of whether…’

- type-definitions/Immutable.d.ts
Refs: https://github.com/facebook/immutable-js/issues/569
> Document usage of Immutable.is() in docs for Iterable.includes and Iterable.has

- README.md
Not sure what is the best wording for this, I'll be happy to change it to your liking.
> Add a link to chai-immutable for testing purposes

- type-definitions/immutable.js.flow
> Set fromJS first argument type to any

- pages/src/src/Header.js
> Fix capitalization of GitHub in docs header

- __tests__/List.ts
Wrote assert functions for Immutable.List.foreach.
> Increase test coverage by writing forEach assertions

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
For a long time now, there have been suggested improvements inline as comments. This removes those comments and implements the improvements.
> Improve typescript definitions by using this and tuples

- dist/immutable.js.flow
- type-definitions/immutable.js.flow
- type-definitions/tests/covariance.js
> Covariant value types in collections.

- __tests__/Record.ts
- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
Adds property access support and fixes mergeIn/mergeDeepIn
> Further improve Record typescript defs

- __tests__/List.ts
> Add test for getIn / setIn / updateIn to List

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- dist/immutable.js.flow
- type-definitions/Immutable.d.ts
- type-definitions/immutable.js.flow
- type-definitions/tests/immutable-flow.js
- type-definitions/tests/record.js
> Overhaul flow type definitions for Record

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
Fixes #890
Fixes #196
Fixes #401
Fixes #228
> Add more docs around what is and isnt safe to use in withMutations

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
> Improve docs for toList()

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
> Explain types at the top of the docs.

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
> Include Note that map & filter always create new instances

- package.json
- pages/lib/markdownDocs.js
- pages/src/docs/src/Defs.js
- pages/src/docs/src/MemberDoc.js
- pages/src/docs/src/SideBar.js
- pages/src/docs/src/TypeDocumentation.js
- pages/src/src/Header.js
- src/IterableImpl.js
- src/List.js
- src/Map.js
- src/OrderedMap.js
- src/OrderedSet.js
- src/Seq.js
- src/Set.js
- src/Stack.js
- yarn.lock
This fixes many issues that were found in 0.21!
> Update to prettier 0.22

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
> Improve flatMap typescript definitions

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
> Explain in docs that keys get coerced to String when converting to Object

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
As suggested in https://github.com/facebook/immutable-js/pull/1035#discussion_r105333309
> Separate type for get() with notSetValue provided.

- .travis.yml
See https://docs.travis-ci.com/user/deployment/script/
> Run deploy docs script only on `master` branch.

- dist/immutable-nonambient.d.ts
- dist/immutable.d.ts
- type-definitions/Immutable.d.ts
* Reducing overrides of functions when possible.
* Using Iterable instead of of Array | Collection.
* Using more specific overrides first.
> Conforming to a number of TS best practices

- pages/src/docs/src/MemberDoc.js
added links to header in docs #356
> added links to header in docs #356

- dist/immutable.js.flow
- type-definitions/immutable.js.flow
- type-definitions/tests/immutable-flow.js
> Fixes missing size property in flow types.

- __tests__/Record.ts
Hello there, just realized the property setter is not tested so this PR :)
> expect setting Record property to throw

- pages/src/docs/src/MemberDoc.js
- pages/src/docs/src/index.js
> Add descriptive titles

- dist/immutable.js.flow
- type-definitions/immutable.js.flow
Per https://github.com/facebook/immutable-js/issues/1308#issuecomment-331061620
Hope we see this in the next release candidate!
> Remove of<T> for Seq

- pages/src/docs/src/Defs.js
Not sure if this is the right way to fix this because i'm unsure about the initial values in the reducers but it definitely fixes #1313 for me and looks fine locally.
> fixed #1313 by fixing two borked reducers

- pages/src/src/StarBtn.js
- pages/src/src/StarBtn.less
Weird bug, seems to be a browser bug which doesn't occur with ```position: relative```.
> fixed #1290 by removing relative position from star count

- type-definitions/Immutable.d.ts
- type-definitions/ts-tests/map.ts
- type-definitions/ts-tests/ordered-map.ts
> Add proper typescript type for flip()

- __tests__/issues.ts
- src/Set.js
> Ensure when OrderedSet becomes empty, that it remains OrderedSet

- __tests__/issues.ts
- src/Set.js
> Ensure set.subtract() accepts any iterable.

- __tests__/issues.ts
- src/utils/quoteString.js
> Do not throw when printing value that cannot be coerced to primitive

- package.json
- resources/rollup-config-es.js
- resources/rollup-config.js
- src/Immutable.js
- yarn.lock
Now you can `Immutable.version` to get an idea of what version you're using.
Wish I had done this a long time ago, it's pretty useful!
Fixes #133
> Include version in build

- pages/src/docs/src/Defs.js
- pages/src/docs/src/SideBar.js
- pages/src/docs/src/TypeDocumentation.js
- pages/src/docs/src/index.js
- type-definitions/Immutable.d.ts
Adds sub types to the sidebar which makes it possible to click and navigate to those links. Fixed issue with "Collection" not loading.
Fixes #1205
> Fix docs website

- type-definitions/immutable.js.flow
- type-definitions/tests/immutable-flow.js
> Flow type: Add special case for `.filter(Boolean)` to remove nulls.

- __tests__/getIn.ts
- src/CollectionImpl.js
> Allow intermediate null value in getIn path.

- type-definitions/immutable.js.flow
> Simplify some flow types - accounting for key specificity

- README.md
Change `depenencnies` → `dependencies`
> FIx a small typo in the README.

- type-definitions/Immutable.d.ts
I had to guess a couple of signatures for the remove function, I hope everything is in order.
> fix: typescript definitions

- .github/CONTRIBUTING.md
Documents steps necessary to run the regression test suite.
> Document regression test steps.

- type-definitions/Immutable.d.ts
Add an example for `subtract()`.
> Add example for OrderedSet subtract.

- pages/lib/runkit-embed.js
- type-definitions/Immutable.d.ts
Because this is pretty weird, and only required to make Runkit work correctly, so reserve it for that case.
> Only include version in require statement in Runkit instances.

- __tests__/splice.ts
- contrib/cursor/README.md
- contrib/cursor/index.d.ts
- type-definitions/Immutable.d.ts
> Fixing some minor typos

- package.json
- yarn.lock
Tested with `yarn build` and `yarn start`
> Update browserify & browser-sync versions

- package.json
- type-definitions/Immutable.d.ts
- yarn.lock
> Support Typescript 3

- __tests__/Set.ts
- src/List.js
- src/Map.js
- src/TrieUtils.js
> Fix issue where refs can recursively collide

- pages/src/docs/src/DocSearch.js
- pages/src/docs/src/SideBar.js
- pages/src/docs/src/style.less
This is the simplest way i found to add it, it can be improved, but I chose to lazy load docsearch; and didn't want to change too much in the css
closes #1501
cc @leebyron, does this what you want? :)
> docs(search): add docsearch

- pages/src/docs/src/DocSearch.js
- pages/src/docs/src/SideBar.js
- pages/src/docs/src/index.js
- pages/src/docs/src/style.less
- pages/src/src/base.less
> Add styles to doc search

- type-definitions/immutable.js.flow
- type-definitions/tests/record.js
Tested by ensuring the flow type tests continue to pass.
> Make a Flow type for Record values optional

- type-definitions/Immutable.d.ts
> [docs] Remove redundant double quotes

- resources/COPYRIGHT
- resources/copyright.js
- resources/rollup-config-es.js
- resources/rollup-config.js
> Gen copyright on dist files

- pages/src/docs/src/Defs.js
- resources/gulpfile.js
> Fix website

- __tests__/.eslintrc.json
- __tests__/ListJS.js
- __tests__/RecordJS.js
- __tests__/utils.js
Follows https://github.com/immutable-js/immutable-js/pull/1833/commits/a9063d2c26d98d62364120a3cfff1877bf0d992a but adds this improvements in .js files too
> Improve DX for tests in JS files too

- src/OrderedSet.js
Migrate https://github.com/immutable-js-oss/immutable-js/pull/216
Fixes #1738 and https://github.com/immutable-js-oss/immutable-js/issues/155
> Fix add zipall to orderedset

- type-definitions/Immutable.d.ts
Complete example with runkit executable
> Better doc for `sortBy`, `maxBy` and `minBy`

- website/src/static/getTypeDefs.ts
Reverts #1852 and applies a better fix
> Fix website docs

- README.md
- website/styles/globals.css
- Adds TOC and does some light reordering/headlining of content
- Removes duplicate lines from OSS merge
- Adds resources found in #1684
- Minor CSS improvements to website for headers
Closes #1684
> Organize README content

- package-lock.json
- package.json
- type-definitions/flow-tests/.flowconfig
- type-definitions/flow-tests/immutable-flow.js
- type-definitions/flow-tests/merge.js
- type-definitions/flow-tests/record.js
- type-definitions/immutable.js.flow
Updates to latest version of flow and resolves all failing test issues.
There seemed to be one slight type declaration refinement which resolved some issues, but the bulk were solved simply by re-arranging the order of the tests, which makes me really uneasy and think that Flow might have some serious type merging bugs
> Flow updated to latest version

- website/src/MarkdownContent.tsx
- website/src/pages/index.tsx
- website/styles/globals.css
> Fix visual regression in docs

- website/src/Header.tsx
- website/src/MarkdownContent.tsx
- website/src/Sidebar.tsx
- website/src/TypeDocumentation.tsx
- website/src/isMobile.ts
- website/src/pages/docs/[version]/[type].tsx
- website/src/pages/docs/[version]/index.tsx
- website/src/pages/docs/index.tsx
- website/src/pages/index.tsx
- website/styles/globals.css
- extract sub-components
- fix `isMobile` function
- migrate to flex and prepare new doc version
> Prepare new version of documentation

- README.md
> No require with import

- CHANGELOG.md
- __tests__/Map.ts
- src/Seq.js
- type-definitions/immutable.d.ts
> Accept Symbol as Map key.

- website/src/pages/docs/[version]/index.tsx
- website/styles/globals.css
Now the website is completely responsive !
> Fixed the text overflow issue in small devices

- CHANGELOG.md
- __tests__/Map.ts
- src/Seq.js
- type-definitions/immutable.d.ts
- website/src/MarkdownContent.tsx
- website/styles/globals.css
Resolves conflicts after updating the `tree-shaking` branch from @bdurrer
> Merge main && Resolve Conflicts

- type-definitions/immutable.js.flow
See working setIn for comparison.
> Fix Flow removeIn types

- __tests__/Set.ts
- src/Set.js
https://github.com/immutable-js/immutable-js/issues/1910
This is my first time contributing to open source so please let me know what else is required
> fix Set.concat to concatenate strings as items

- type-definitions/immutable.d.ts
- type-definitions/ts-tests/list.ts
- type-definitions/ts-tests/map.ts
> TS: `update` method may return `undefined`

- type-definitions/immutable.d.ts
- type-definitions/ts-tests/from-js.ts
> Fix fromJS declaration for greater compatibility

- type-definitions/immutable.d.ts
> Fix isOrderedSet type

- CHANGELOG.md
- type-definitions/immutable.d.ts
- type-definitions/ts-tests/deepCopy.ts
- type-definitions/ts-tests/record.ts
> Merge main into 5.x

- resources/dist-stats.mjs
Make bundlephobia error code understable in CI
> handle error with bundlephobia

- package-lock.json
- package.json
TSTyche 2 got published today. Let’s upgrade?
> chore: upgrade TSTyche to v2

- __tests__/Range.ts
- src/Operations.js
> Fix issue with slice negative of filtered sequence

- package-lock.json
- package.json
- type-definitions/immutable.d.ts
- type-definitions/ts-tests/map.ts
- type-definitions/ts-tests/set.ts
> Map and Set sort and sortBy return type

- website/src/app/docs/[version]/layout.tsx
https://github.com/immutable-js/immutable-js/pull/1983 did migrate docs to nextjs new navigation, but I forgot to add the layout file.
> doc: missing layout

- __tests__/concat.ts
- src/Iterator.js
- src/Operations.js
Hello!
This is a fix for a 2 years old issue: https://github.com/immutable-js/immutable-js/issues/1915
Let me know if you have any question or feel some stuffs should be done differently.
Cheers
> Fix issue 1915

- type-definitions/ts-tests/seq.ts
> test Seq.concat typing

- __tests__/functional/get.ts
- __tests__/functional/has.ts
- __tests__/functional/remove.ts
- __tests__/functional/set.ts
- __tests__/functional/update.ts
- eslint.config.mjs
Functional directory is partially tested.
Let's add some tests here for missing functions.
> Test functional directory

- __tests__/getIn.ts
- __tests__/updateIn.ts
- type-definitions/immutable.d.ts
- type-definitions/ts-tests/functional.ts
In order to prepare [migration to TS](https://github.com/immutable-js/immutable-js/pull/2063) of functional directory, let's improve the typings
> Update functional types

- __tests__/Record.ts
- __tests__/RecordJS.js
- __tests__/utils.js
- src/Record.js
- src/Repeat.js
Follows https://github.com/immutable-js/immutable-js/pull/2041 where all factories method have been created except Record
Fix two other small issues : 
- missing a `new RepeatImpl` instead of `new Repeat`
- replace a wrong `new List` -> `List`
> Migrate Record to a factory class

- .github/workflows/ci.yml
- package.json
- resources/check-build-output.cjs
To avoid the 5.1.0 issue : https://github.com/immutable-js/immutable-js/releases/tag/v5.1.1
> Ensure files are properly builded

- package.json
- resources/check-build-output.mjs
- resources/jestResolver.js
- resources/rollup-config.mjs
> Define "exports" in package.json

- package-lock.json
- package.json
- website/src/app/layout.tsx
- website/src/app/play/page.tsx
- website/src/repl/Editor.tsx
- website/src/repl/Repl.tsx
- website/src/useDarkMode.ts
- website/styles/globals.css
- website/styles/prism-theme.css
> Dark mode for documentation

- website/src/app/play/Playground.tsx
- website/src/app/play/encoder.ts
- website/src/app/play/page.tsx
- website/src/repl/Repl.tsx
Record code in the url hash, to allow bookmark or copy / paste.
https://github.com/user-attachments/assets/d89ad6f7-476e-42d0-8caa-4c6241b7d726
> Encode code to / decode code from the URL hash.

- website/src/repl/Repl.tsx
- website/src/worker/index.ts
- website/src/worker/jsonml-types.ts
- website/src/worker/normalizeResult.ts
In order to avoid undetected bug, and to improve the REPL worker script, let's move it to a proper file.
> extract repl worker script to a proper file

- eslint.config.mjs
- jest.config.mjs
- package-lock.json
- package.json
- website/src/repl/FormatterOutput.tsx
- website/src/repl/Repl.tsx
- website/src/worker/jsonml-types.test.ts
- website/src/worker/jsonml-types.ts
- website/src/worker/normalizeResult.test.ts
- website/src/worker/normalizeResult.ts
> Deep formatter in playground

- __tests__/merge.ts
- src/methods/merge.js
> Merge should work with empty record

- website/src/app/WorkerContext.tsx
- website/src/app/layout.tsx
- website/src/repl/Repl.tsx
- website/src/worker/index.ts
actually, we load one separate worker for each REPL.
We now only use one worker.
> only one worker for REPL

- README.md
- type-definitions/immutable.d.ts
- website/docs/Collection.Keyed.mdx
- website/docs/List.mdx
- website/docs/Seq.Keyed.mdx
- website/docs/isImmutable().mdx
- website/docs/isKeyed().mdx
There are some missing imports in the documentation. 
Let's migrate the latest require to import
> Require to import

- __tests__/ArraySeq.ts
- __tests__/Conversion.ts
- __tests__/Equality.ts
- __tests__/KeyedSeq.ts
- __tests__/List.ts
- __tests__/Map.ts
- __tests__/OrderedSet.ts
- __tests__/Predicates.ts
- __tests__/Seq.ts
- __tests__/Set.ts
- __tests__/Stack.ts
- __tests__/functional/get.ts
- __tests__/groupBy.ts
- __tests__/issues.ts
- __tests__/merge.ts
- __tests__/slice.ts
- __tests__/splice.ts
- __tests__/transformerProtocol.ts
- __tests__/tsconfig.json
- __tests__/updateIn.ts
- package-lock.json
- package.json
- resources/jestPreprocessor.js
Now that a proper tsconfig file has been add into the repo, let's extends it for tests.
>  Use default tsconfig for tests

- __tests__/utils/arrCopy.ts
Prepare fix on v6 branch for #2098 : let's add some test on main branch first.
> add tests for arrCopy

- src/CollectionHelperMethods.ts
- src/CollectionImpl.js
- src/utils/hasCollection.ts
Take https://github.com/immutable-js/immutable-js/commit/d7a41f78eda15f7d54e6f9b6ea518f1671d38bf2#diff-e07884517d664b4d4195610350d28217383ae084398b98be4eba6d0658548489 from 6.x into main. 
Extract some other utils that can be converted to TS.
> Extract CollectionHelperMethods

- package-lock.json
- package.json
- website/src/DocSearch.tsx
- website/styles/globals.css
> Fix algolia search

- package-lock.json
- package.json
- src/Collection.ts
- src/functional/get.ts
- src/predicates/isIndexed.ts
While upgrading to TS 5.9, I encountered the same issue than #2134.
This should be the proper fix.
```
Type '(Iterable<T> | ArrayLike<T>) & IndexedCollectionImpl<unknown>' is not assignable to type 'IndexedCollectionImpl<T>'.
Type 'Iterable<T> & IndexedCollectionImpl<unknown>' is not assignable to type 'IndexedCollectionImpl<T>'.
The types returned by 'toArray()' are incompatible between these types.
Type 'unknown[]' is not assignable to type 'T[]'.
Type 'unknown' is not assignable to type 'T'.
'T' could be instantiated with an arbitrary type which could be unrelated to 'unknown'.
113   return isIndexed(value) ? value : IndexedSeq(value);
```
> Upgrade and test TS 5.9
